INSERT INTO USER_DETAILS(ID, BIRTH_DATE, NAME)
VALUES(1, current_date(), 'PARK');

INSERT INTO USER_DETAILS(ID, BIRTH_DATE, NAME)
VALUES(2, current_date(), 'JUN');

INSERT INTO USER_DETAILS(ID, BIRTH_DATE, NAME)
VALUES(3, current_date(), 'YONG');

INSERT INTO POST(ID, CONTENT, USER_ID)
VALUES(101, 'I Want To Learn AWS', 1);
INSERT INTO POST(ID, CONTENT, USER_ID)
VALUES(102, 'I Want To Learn SpringBoot', 1);

INSERT INTO POST(ID, CONTENT, USER_ID)
VALUES(103, 'I Want To Learn English', 2);
INSERT INTO POST(ID, CONTENT, USER_ID)
VALUES(104, 'I Want To Be DevOpsDev', 2);
